FROM ubuntu:22.04
RUN apt-get -o Acquire::Retries=5 update && apt-get -o Acquire::Retries=5 install -y --no-install-recommends \
      ca-certificates \
      file \
      g++-aarch64-linux-gnu \
      make \
      pkg-config \
      python3 \
      tar \
      zip \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /work
