FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -o Acquire::Retries=5 update \
 && apt-get -o Acquire::Retries=5 install -y --no-install-recommends \
      ca-certificates \
      file \
      g++-aarch64-linux-gnu \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /work
